version: 0.2

phases:
    install:
        - apt-get install -y maven
        runtime-versions:
            java: openjdk8
    pre_build:
        commands:
            - echo nothing to do in prebuild
    build:
        commands:
            - echo Entered the build phase...
            - echo Build started on 'date'
            -mvn install
    post_build:
        commands:
            - echo Build completed on 'date'
    artifacts:
        files:
            - target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
